---
title: "Get NBA data from other days"
author: "Guillem Bassa"
date: "5/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```


```{r}
library(rvest)
library(RSelenium)
library(tidyverse)
library(janitor)

```

Open the page with the filter of exact day

```{r}
pagina <-"https://www.nba.com/stats/players/traditional/?sort=PLUS_MINUS&dir=-1&Season=2020-21&SeasonType=Regular%20Season&DateFrom=01%2F06%2F2021&DateTo=01%2F06%2F2021"
  
  
  #mostra   "https://www.nba.com/stats/players/traditional/?sort=PTS&dir=-1&Season=2020-21&SeasonType=Regular%20Season&LastNGames=1"
```

Posar la data


```{r}
match_day <- "2021-01-06"
  
  
#Format: "2021-01-05"
 

```







MIRAR QUE LO DE DALT ESTIGUI FICAT!!!


```{r}
browser <- rsDriver(browser = "firefox", port = 4545L, verbose = FALSE)
remDr <- browser[["client"]]

remDr$navigate(pagina)

Sys.sleep(15)

remDr$findElement(using = 'id', "onetrust-accept-btn-handler")$clickElement()

Sys.sleep(7)

remDr$findElement(using = 'xpath', "//*/option[@value = 'string:All']")$clickElement()
```

Get the html


```{r}
page_html <- remDr$getPageSource()[[1]]
table_html <- read_html(page_html) %>% #trobar la taula
  html_nodes("table") %>% 
  html_table(fill=T)


table_html_stats <- as.data.frame(table_html[[1]])

table_html_stats <- table_html_stats %>%
  rename(pos = 1) %>% 
  mutate(`3PTMissed` = `3PA` - `3PM`,
         `FG_Missed`= FGA - FGM,
         FTMissed = FTA - FTM)
```

Modify the df

```{r}
table_html_stats <- table_html_stats %>% 
  select(-pos) %>% 
  mutate(score = PTS -FG_Missed - FTMissed + REB + AST +STL +BLK - TOV -PF + (W*2),
         day = match_day)

```
Save the file

```{r}
save_name <- as.character(paste0("C:/Users/Guillem/Documents/GitHub/Fantasy-NBA-2021//",as.character(match_day),"_Data.csv"))

write.csv(table_html_stats,save_name, row.names = FALSE)
```


Get the master and merge the day

```{r}
master_read <- as.character(as.Date(match_day)-1)
master_read_ok <- 
  as.character(paste0(master_read,"_Master.csv"))


master <- read.csv(master_read_ok)
colnames(table_html_stats) <- colnames(master) 
  

master <- rbind(as.data.frame(master), as.data.frame(table_html_stats))

master_save <- as.character(paste0("C:/Users/Guillem/Documents/GitHub/Fantasy-NBA-2021//",as.character(match_day),"_Master.csv"))
  
write.csv(master,master_save, row.names = FALSE)


```

```{r}


```


