---
title: "NBA studio"
author: "Guillem Bassa"
date: "5/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```


```{r}
library(rvest)
library(RSelenium)
library(tidyverse)
library(janitor)

```

Open the page

```{r}
insert_day <- format((Sys.Date()-1), format = "%d")
insert_month <-format((Sys.Date()-1), format = "%m")
insert_year <- format((Sys.Date()-1), format = "%y")


pagina <- as.character(paste0("https://www.nba.com/stats/players/traditional/?sort=PTS&dir=-1&Season=2020-21&SeasonType=Regular%20Season&DateFrom=",insert_month,"%2F",insert_day,"%2F20", insert_year, "&DateTo=",insert_month,"%2F",insert_day,"%2F20", insert_year)) 


browser <- rsDriver(browser = "firefox", port = 4545L, verbose = FALSE)
remDr <- browser[["client"]]

remDr$navigate(pagina)

Sys.sleep(20)

remDr$findElement(using = 'id', "onetrust-accept-btn-handler")$clickElement()

Sys.sleep(15)

remDr$findElement(using = 'xpath', "//*/option[@value = 'string:All']")$clickElement()
```

Get the html


```{r}
page_html <- remDr$getPageSource()[[1]]
table_html <- read_html(page_html) %>% #trobar la taula
  html_nodes("table") %>% 
  html_table(fill=T)


table_html_stats <- as.data.frame(table_html[[1]])

table_html_stats <- table_html_stats %>%
  rename(pos = 1) %>% 
  mutate(`3PTMissed` = `3PA` - `3PM`,
         `FG_Missed`= FGA - FGM,
         FTMissed = FTA - FTM)
```

Modify the df

```{r}
table_html_stats <- table_html_stats %>% 
  select(-pos) %>% 
  mutate(score = PTS -FG_Missed - FTMissed + REB + AST +STL +BLK - TOV -PF + (W*2),
         day = as.factor(Sys.Date()-1))

```
Save the file

```{r}
save_name <- as.character(paste0("C:/Users/Guillem/Documents/GitHub/Fantasy-NBA-2021//",as.character(Sys.Date()-1),"_Data.csv"))

write.csv(table_html_stats,save_name, row.names = FALSE)
```

Get the master and merge the day

```{r}
read_master <- as.character(paste0("C:/Users/Guillem/Documents/GitHub/Fantasy-NBA-2021//",as.character(Sys.Date()-2),"_Master.csv"))

master <- read.csv(read_master)

colnames(table_html_stats) <- colnames(master) 

master <- rbind(master, table_html_stats)

master_save <- as.character(paste0("C:/Users/Guillem/Documents/GitHub/Fantasy-NBA-2021//",as.character(Sys.Date()-1),"_Master.csv"))
master_save
  
write.csv(master,master_save, row.names = FALSE)


```







